### ISSUE TITLE
Selecting 'other' as license type creates display issue for record

### ISSUE THREAD

**Issue by jhallida** [samvera-labs/chimera#22]
### Descriptive summary
When I select 'other' as a license type, and fill in a license description, it creates a problem with how the record will be displayed. There is an extra, bogus row in the item display that says "CC License" with a link that says "Other". Clicking the link creates a "Record Not Found" exception.

### Expected behavior (if bug)
This row with the bad link should not be displayed.

### Actual behavior (if bug)
Row with bad link is displayed

### Steps to reproduce the behavior (if bug)
1. Create a record. Give it a license type of 'other' and fill in any license in the other license field.
2. Look at the record once it saves. The bogus row will be displayed.

**Comment by fritzfreiheit** [comment]
This should be fixed by the Chimera-27
