### ISSUE TITLE
Updates from Deepblue between v1.0.0 and v1.0.1

### ISSUE THREAD

**Issue by fritzfreiheit** [samvera-labs/chimera#27]
### Descriptive summary
Updates committed to Deepblue since Jan. 10th, 2019 when v1.0.0 was cut and v1.0.1 was cut on Feb. 28th, 2019. BLUEDOC-### reference Jira tickets. Most will be reflected in Deepblue PRs (that is, you can search on BLUEDOC-### as part of the committed branch names).

* BLUEDOC 366 -- DOI minting service changed
* BLUEDOC 367 -- Add markup for fields to be indexed by Google Dataset Search
* BLUEDOC 369 -- Announcement banner
* BLUEDOC 372 -- Work's provenance log entries are now visible through UI for admins.
* BLUEDOC 374 -- Globus copy job sets copied file permissions and group correctly allowing copied files to be accessed by globus.
* BLUEDOC 376 -- File manager changes sometimes not saved -- Added debug logging code
* BLUEDOC 381 -- Admins can now download all files for a work regardless of visibility
* BLUEDOC 382 -- Dashboard notification links to works now are correct (no /data/data/)
* BLUEDOC 383 -- Virus scanning for new versions of files is now occuring (data modified for file sets is not updating)
* BLUEDOC 384 -- Other funding agency other value now saves
* BLUEDOC 386 -- Globus copy file target permissions and group configurable
* BLUEDOC 389 -- Bulk file upload files sometimes go missing -- Added debug logging code -- Changed the upload process to run only job in background to attach and ingest files, and added more worker threads for ingest process.
* BLUEDOC 390 -- Create work rds email changed back to standard rds email
* BLUEDOC 392 -- Message for downloads between 1GB and 10GB now says the download *may* not work, try Globus
* BLUEDOC 396 -- References to ScholarsArchive gem removed
* BLUEDOC 397 -- Admins now have full access to change work's visibility (open, embargo, institution, restricted)
* BLUEDOC 414 -- New version of files now show actual uploading user (note that the depositor remains the same)
* BLUEDOC 415 -- Workflow transition to deposited now generates an email to RDS and logs in provenance
* BLUEDOC 419 -- Updated gem dependencies for security alert

**Comment by jhallida** [comment]
Merged
