### ISSUE TITLE
Remove to_yaml_properties

### ISSUE THREAD

**Issue by fritzfreiheit** [samvera-labs/chimera#29]
### Descriptive summary

Remove to_yaml_properties as it was deprecated and removed in ruby 2.5

### Rationale

Removed in ruby 2.5

### Expected behavior (if bug)

Not throw:

NoMethodError (undefined method `to_yaml_properties' for #<Tempfile:/tmp/RackMultipart20190305-19507-1eqa4hk.jpg>)

### Actual behavior (if bug)

Throws: NoMethodError (undefined method `to_yaml_properties' for #<Tempfile:/tmp/RackMultipart20190305-19507-1eqa4hk.jpg>)

### Steps to reproduce the behavior (if bug)

1. Upload a file

**Comment by jhallida** [comment]
Merged
