### ISSUE TITLE
Email user and managers when file uploads are complete

### ISSUE THREAD

**Issue by fritzfreiheit** [samvera-labs/chimera#33]
### Descriptive summary

Email user and managers when file upload, ingest, and attach to work are complete.

### Rationale

File ingest (an asynchronous process) can take a significant amount of time. Inform the user when it's done.

### Acceptance Criteria
- [ ] User is emailed when file ingest is complete with a list of files attached.
- [ ] Managers are email when the file ingest is complete with a list of files attached.

**Comment by jhallida** [comment]
Merged
