### ISSUE TITLE
 Embargo deactivate should apply after embargo visibility

### ISSUE THREAD

**Issue by fritzfreiheit** [samvera-labs/chimera#35]
### Descriptive summary

Embargo does not apply after embargo visibility after deactivation. This is also true of lease.

### Rationale

Embargo and lease have contracted to set a visibility after they are deactivated. It should do so.

### Expected behavior (if bug)

Set a work's visibility to the one specified by visibility_after_embargo.

### Actual behavior (if bug)

Always sets restricted visibility after embargo is deactivated.

### Steps to reproduce the behavior (if bug)

Create an embargo with a visibility after deactivation so something other than restricted.

**Comment by jhallida** [comment]
Merged
