### ISSUE TITLE
re-enable citation feature from Hyrax and see if it meets our needs

### ISSUE THREAD

**Issue by jhallida** [samvera-labs/chimera#40]
### Descriptive summary
We need the citation feature, and Hyrax by default has one. Let's figure out if it can be re-enabled easily, and if so, see if it meets our needs or needs to be modified.

**Comment by njaffer** [comment]
sample citation: https://nurax-dev.curationexperts.com/concern/images/b2773v83m?locale=en#?c=0&m=0&s=0&cv=0&xywh=-654%2C-44%2C1863%2C853
